# ASSIGNMENT 1
## Data Exploration and Data Cleaning Using Pandas

### Submitted By:
**Priyanshu Tiwari** 

Maharishi Markandeshwar (Deemed to be University)

### Objective:
The objective of this assignment is to perform data exploration and data preprocessing operations using the Pandas library in Python. The task includes loading a CSV dataset, analyzing the dataset structure, handling missing values, performing filtering and selection operations, removing duplicate records, creating derived columns, and exporting the cleaned dataset for future analytical purposes.

In [2]:
#Import Required Libraries

import pandas as pd

print("Pandas library imported successfully!")

Pandas library imported successfully!

# Question 1: Load a CSV Dataset into a Pandas DataFrame

In this step, the CSV dataset is loaded into a Pandas DataFrame using the Pandas library for further data analysis and preprocessing.

In [3]:
# Loading CSV dataset

df = pd.read_csv("tshirts.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [4]:
# Displaying first 5 rows

df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,17352320,ether,Kora Collection Blue Sustainable Naturally Dye...,4.4,70,1099.0,47.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/173...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":7,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",NaN,"[{""size"":""XS"",""value"":""32.0in"",""value_name"":""T...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
1,17403950,Mast & Harbour,Men Mint Green Typography Printed T-shirt,4.2,200,899.0,NaN,"""₹899.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":14,""2_stars"":10,""3_stars"":16,""4_star...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Tru███m R███il,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17403950_cae700""]",Sho███o. ███-10█████████enu███████████████████...,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
2,17404018,Mast & Harbour,Men Blue & White Striped Regular Fit T-shirt,3.9,72,999.0,NaN,"""₹999.00""",INR,http://assets.myntassets.com/assets/images/174...,...,"{""1_star"":6,""2_stars"":6,""3_stars"":9,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...","[""rw-17404018_cae700""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
3,22143924,Urbano Plus,Size Typography Printed Cotton T-shirt,3.2,6,1099.0,45.0,"""₹1,099.00""",INR,http://assets.myntassets.com/assets/images/221...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""XXL"",""value"":""47.0in"",""value_name"":""...",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",tshirts
4,14619398,ScoldMe,Women Multicoloured Pack Of 2 Slim Fit T-shirt,0.0,0,1598.0,55.0,"""₹719.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,SUN███E C███TIO███,"[{""size"":""S"",""value"":""31.0in"",""value_name"":""Bu...",NaN,"No.███han███Gou█████████ut,███████████████████...","[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},...","{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

# Question 2: Explore Data (head/tail, shape, columns, data types)

In this step, the dataset structure and basic information are explored using different Pandas functions.

In [5]:
# Displaying last 5 rows

df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
34,22629260,max,Striped Polo Collar Short Sleeves T-shirt,4.4,7,799.0,40.0,"""₹479.00""",INR,http://assets.myntassets.com/assets/images/226...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Lan███rk ███ine█████████t L███,"[{""size"":""S"",""value"":""36.0in"",""value_name"":""Ch...",NaN,#41███42/███bla█████████ pa███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
35,19291812,Mad Over Print,Women Black Love Wins Oversize T-shirt,4.8,5,1599.0,58.0,"""₹671.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",MAD███R P███T P█████████MIT███,"[{""size"":""S"",""value"":""39.3in"",""value_name"":""Bu...",NaN,621███ 6n███ kh█████████zia███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
36,19206288,FERANOID,Men Purple Henley Neck Bio Finish T-shirt,4.2,21,1199.0,50.0,"""₹599.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":5,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Fer███id,"[{""size"":""S"",""value"":""38.0in"",""value_name"":""Ch...",NaN,B15███ SH███MAR█████████RK ███████████████████...,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
37,19264534,Flying Machine,Men Black & White Printed Pure Cotton Slim Fit...,4.0,102,999.0,61.0,"""₹389.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":8,""2_stars"":4,""3_stars"":15,""4_stars""...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10T███LOO███DU █████████ITY███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts
38,19264536,Flying Machine,Men Rust Orange Melange Pure Cotton Slim Fit T...,3.8,60,1299.0,61.0,"""₹506.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":5,""2_stars"":7,""3_stars"":7,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""XS"",""value"":""34.0in"",""value_name"":""C...",NaN,10T███LOO███DU █████████ITY███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",tshirts

In [6]:
# Shape of dataset

print("Shape of Dataset:", df.shape)

Shape of Dataset: (39, 24)

In [7]:
# Displaying column names

print(df.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

# Question 3: Handle Missing Values (identify, fill/drop)

In this step, missing values are identified and handled using suitable techniques.

In [8]:
# Checking missing values

print(df.isnull().sum())

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   7
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said        9
seller_name               21
sizes                      0
videos                    29
seller_information        21
variations                25
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [9]:
# Selecting numeric columns

numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns

print("Numeric Columns:")
print(numeric_columns)

Numeric Columns:
Index(['product_id', 'rating', 'ratings_count', 'initial_price', 'discount'], dtype='str')

In [10]:
# Filling numeric missing values with mean

for col in numeric_columns:
    
    df[col] = df[col].fillna(df[col].mean())

print("Numeric missing values handled successfully!")

Numeric missing values handled successfully!

In [17]:
# Selecting categorical columns

categorical_columns = df.select_dtypes(include=['object']).columns

print("Categorical Columns:")
print(categorical_columns)

Categorical Columns:
Index(['title', 'product_description', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

C:\Users\Priya\AppData\Local\Temp\ipykernel_18820\2002694160.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object']).columns

In [18]:
# Filling categorical missing values with mode

for col in categorical_columns:
    
    df[col] = df[col].fillna(df[col].mode()[0])

print("Categorical missing values handled successfully!")

Categorical missing values handled successfully!

In [19]:
# Checking missing values again

print(df.isnull().sum())

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

# Question 4: Perform Basic Operations (filter rows, select columns)

In this step, basic data operations such as column selection and row filtering are performed.

In [20]:
# Selecting first two columns

selected_columns = df.iloc[:, :2]

print(selected_columns.head())

   product_id           title
0    17352320           ether
1    17403950  Mast & Harbour
2    17404018  Mast & Harbour
3    22143924     Urbano Plus
4    14619398         ScoldMe

In [21]:
# Filtering rows using numeric column

numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

filtered_data = df[df[numeric_cols[0]] > df[numeric_cols[0]].mean()]

print(filtered_data.head())

   product_id           title  \
0    17352320           ether
1    17403950  Mast & Harbour
2    17404018  Mast & Harbour
3    22143924     Urbano Plus
7    18817326  Tommy Hilfiger

                                 product_description  rating  ratings_count  \
0  Kora Collection Blue Sustainable Naturally Dye...     4.4             70
1          Men Mint Green Typography Printed T-shirt     4.2            200
2       Men Blue & White Striped Regular Fit T-shirt     3.9             72
3             Size Typography Printed Cotton T-shirt     3.2              6
7  Men Beige & Navy Blue Striped Pure Cotton T-shirt     4.4             58

   initial_price  discount  final_price currency  \
0         1099.0   47.0000  "₹1,099.00"      INR
1          899.0   52.3125    "₹899.00"      INR
2          999.0   52.3125    "₹999.00"      INR
3         1099.0   45.0000  "₹1,099.00"      INR
7         2799.0   40.0000  "₹2,799.00"      INR

                                              images  ...  \
0  http://assets.myntassets.com/assets/images/173...  ...
1  http://assets.myntassets.com/assets/images/174...  ...
2  http://assets.myntassets.com/assets/images/174...  ...
3  http://assets.myntassets.com/assets/images/221...  ...
7  http://assets.myntassets.com/assets/images/188...  ...

                                     amount_of_stars  \
0  {"1_star":2,"2_stars":1,"3_stars":7,"4_stars":...
1  {"1_star":14,"2_stars":10,"3_stars":16,"4_star...
2  {"1_star":6,"2_stars":6,"3_stars":9,"4_stars":...
3  {"1_star":2,"2_stars":1,"3_stars":0,"4_stars":...
7  {"1_star":5,"2_stars":0,"3_stars":2,"4_stars":...

                                 what_customers_said  \
0  [{"percentage":"100","value_name":"Fit, Just R...
1  [{"percentage":"67","value_name":"Fit, Just Ri...
2  [{"percentage":"67","value_name":"Fit, Just Ri...
3  [{"percentage":"100","value_name":"Fit, Just R...
7  [{"percentage":"67","value_name":"Fit, Just Ri...

                         seller_name  \
0  ARV███ LI███TYL█████████LIM██████
1                     Tru███m R███il
2  ARV███ LI███TYL█████████LIM██████
3  ARV███ LI███TYL█████████LIM██████
7  ARV███ LI███TYL█████████LIM██████

                                               sizes  \
0  [{"size":"XS","value":"32.0in","value_name":"T...
1  [{"size":"S","value":"38.0in","value_name":"Ch...
2  [{"size":"S","value":"38.0in","value_name":"Ch...
3  [{"size":"XXL","value":"47.0in","value_name":"...
7  [{"size":"S","value":"38.03in","value_name":"C...

                                              videos  \
0  ["https://videos.myntassets.com/assets/videos/...
1                             ["rw-17403950_cae700"]
2                             ["rw-17404018_cae700"]
3  ["https://videos.myntassets.com/assets/videos/...
7  ["https://videos.myntassets.com/assets/videos/...

                                  seller_information variations best_offer  \
0  10T███LOO███DU █████████ITY███████████████████...       [{}]         {}
1  Sho███o. ███-10█████████enu███████████████████...       [{}]         {}
2  10T███LOO███DU █████████ITY███████████████████...       [{}]         {}
3  10T███LOO███DU █████████ITY███████████████████...    [{},{}]         {}
7  10T███LOO███DU █████████ITY███████████████████...       [{}]         {}

                                         more_offers category
0  [{"offer_name":"10% Instant Discount on Citi C...  tshirts
1  [{"offer_name":"10% Instant Discount on Citi C...  tshirts
2  [{"offer_name":"10% Instant Discount on Citi C...  tshirts
3  [{"offer_name":"10% Instant Discount on Citi C...  tshirts
7  [{"offer_name":"10% Instant Discount on Citi C...  tshirts

[5 rows x 24 columns]

# Question 5: Remove Duplicates

In this step, duplicate rows are identified and removed from the dataset.

In [22]:
# Checking duplicate rows

print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [23]:
# Removing duplicate rows

df = df.drop_duplicates()

print("Duplicate rows removed successfully!")

Duplicate rows removed successfully!

In [24]:
print(df.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

# Question 6: Create a Derived Column (total_amount = price × quantity)

In this step, a new derived column named total_amount is created using the price and quantity columns.

In [25]:
# Creating price and quantity columns

df['price'] = df['initial_price'] - df['discount']

df['quantity'] = df['ratings_count']

In [26]:
# Creating total_amount column

df['total_amount'] = df['price'] * df['quantity']

print("New column created successfully!")

print(df[['price', 'quantity', 'total_amount']].head())

New column created successfully!
       price  quantity  total_amount
0  1052.0000        70       73640.0
1   846.6875       200      169337.5
2   946.6875        72       68161.5
3  1054.0000         6        6324.0
4  1543.0000         0           0.0

# Question 7: Save Cleaned Dataset

In this step, the cleaned dataset is saved as a new CSV file for future use.

In [27]:
# Saving cleaned dataset

df.to_csv("cleaned_tshirts.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

# Brief Summary

In this assignment, the dataset was loaded and explored using the Pandas library. Missing values were identified and handled using different techniques. Basic operations like filtering rows and selecting columns were performed. Duplicate rows were removed from the dataset. A new column named total_amount was created using price and quantity values. Finally, the cleaned dataset was saved as a new CSV file for future analysis.